version: "3"

services:
  faker:
    container_name: faker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: faker
      SLEEP_TIME: 30

networks:
  default:
    external:
      name: kafka-network
