version: "3"

services:
  dash-app:
    container_name: dash-app
    hostname: dash-app
    image: dash-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
      WEATHER_TABLE: weatherreport
      TWITTER_TABLE: twitterdata
      FAKER_TABLE: fakerdata
      KRAKEN_TABLE: kraken_tick_data
      CRYPTOPANIC_TABLE: cryptopanic_news
    ports:
      - 8050:8050
    restart: unless-stopped

networks:
  default:
    external: true
    name: cassandra-network
