version: "3"

services:
  dash-app:
    container_name: dash-app
    hostname: dash-app
    image: dash-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
      WEATHER_TABLE: weatherreport
      TWITTER_TABLE: twitterdata
      FAKER_TABLE: fakerdata
      KRAKEN_TABLE: kraken_tick_data
      CRYPTOPANIC_TABLE: cryptopanic_news
      ANALYSIS_REPORT_TABLE: analysis_report
      AWS_ACCESS_KEY_ID: PLEASE_FILL_IN
      AWS_SECRET_ACCESS_KEY: PLEASE_FILL_IN
      AWS_DEFAULT_REGION: us-east-2
    ports:
      - 8050:8050
    restart: unless-stopped

networks:
  default:
    external: true
    name: cassandra-network
