version: "3"

services:
  twitter_service:
    container_name: twitter_service
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: ${TWEET_TOPIC}
      BATCH_SIZE: ${TWEET_BATCH_SIZE}

networks:
  default:
    external:
      name: kafka-network
