version: "3"

services:
  datavis:
    container_name: datavis
    hostname: datavis
    image: datavis
    build: .
    environment:
      CASSANDRA_HOST: cassandradb
      CASSANDRA_KEYSPACE: kafkapipeline
      WEATHER_TABLE: weatherreport
      TWITTER_TABLE: twitterdata
      FAKER_TABLE: fakerdata
    ports:
      - 8888:8888
    volumes:
      - visdata:/usr/app
volumes:
  visdata:

networks:
  default:
    external:
      name: cassandra-network
