version: "3"

services:
  cryptopanic:
    container_name: cryptopanic
    image: cryptopanic-producer_cryptopanic
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: cryptopanic
      SLEEP_TIME: 1800

networks:
  default:
    external:
      name: kafka-network
