version: "3"

services:
  kraken:
    container_name: kraken
    image: kraken-producer_kraken
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: kraken

networks:
  default:
    external:
      name: kafka-network
